# Generated by Django 3.2.23 on 2023-12-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0003_isbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
    ]
