# Generated by Django 3.2.23 on 2023-11-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0007_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('آرایشی', 'arayeshi'), ('خوراکی', 'خوارکی'), ('پوشاک', 'پوشاک')], default='آرایشی', max_length=20),
        ),
    ]
