# Generated by Django 3.2.23 on 2023-11-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0008_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='cat',
        ),
    ]
