# Generated by Django 3.2.23 on 2023-11-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0011_alter_products_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.CharField(blank=True, choices=[('arayeshi', 'arayeshi'), ('خوراکی', 'خوارکی'), ('پوشاک', 'پوشاک')], default='arayeshi', max_length=20, null=True),
        ),
    ]
