# Generated by Django 3.2.23 on 2023-11-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0013_alter_products_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.CharField(choices=[('arayeshi', 'arayeshi'), ('khorak', 'khorak'), ('pushaak', 'pushaak')], default='arayeshi', max_length=20),
        ),
    ]
