# Generated by Django 3.2.23 on 2023-11-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0014_alter_products_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.CharField(choices=[(1, 'arayeshi'), (2, 'khorak'), ('pushaak', 'pushaak')], default='arayeshi', max_length=20),
        ),
    ]
