# Generated by Django 3.2.23 on 2023-11-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0015_alter_products_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
