# Generated by Django 3.2.23 on 2023-11-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0019_products_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_exist',
            field=models.BooleanField(default=True),
        ),
    ]
