# Generated by Django 3.2.23 on 2023-11-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0022_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
