# Generated by Django 3.2.23 on 2023-11-20 21:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0025_remove_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[450, 300], upload_to=''),
        ),
    ]
