# Generated by Django 3.2.23 on 2023-11-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0028_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='star',
        ),
    ]
