# Generated by Django 3.2.23 on 2023-11-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0030_products_star'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category'},
        ),
    ]
