# Generated by Django 3.2.23 on 2023-11-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0031_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
