# Generated by Django 3.2.23 on 2023-11-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0035_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
