# Generated by Django 3.2.23 on 2023-11-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0036_products_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
