# Generated by Django 3.2.23 on 2023-11-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0037_remove_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
